### ISSUE TITLE
Questions about Bilevel optimization

### ISSUE THREAD

**Issue by haebeom-lee** [alinlab/L2T-ww#10]
Hi, I really enjoyed reading your paper, and I learned a lot!

I have a simple question. In your algorithm, when constructing the bilevel optimization framework, it seems that L_org does not distinguish between train and val. It means that the inner L_org and the outer L_org comes from the same (training) dataset. Can I learn the intuition of this setting (because most of bilevel optimization assumes exclusive train / val set for inner / outer)? 

Thank you!

**Comment by hankook** [comment]
I appreciate your interest in our paper.

Our intuition is that using different objectives in inner and outer loops makes the same sample available to use in both inner/outer loops. This is because it does not cause an overfitting issue. This advantage allows us to use a smaller number of iterations in the inner loop since the inner loop directly optimizes models with respect to the sample.

**Comment by haebeom-lee** [comment]
Thank you !!
